name: Build Electron app
on:
  push:
    tags:
      - v*
    paths-ignore:
      - packages/functions/**
      - packages/web/**

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn app make
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: packages/app/out/make/squirrel.windows/x64/*.exe
